/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DemoTrpcTodoRouteImport } from './routes/demo.trpc-todo'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo.table'
import { Route as DemoStoreRouteImport } from './routes/demo.store'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as ExampleGuitarsIndexRouteImport } from './routes/example.guitars/index'
import { Route as AdminRhIndexRouteImport } from './routes/admin/rh/index'
import { Route as AdminCoreIndexRouteImport } from './routes/admin/core/index'
import { Route as AdminAlmoxarifadoIndexRouteImport } from './routes/admin/almoxarifado/index'
import { Route as ExampleGuitarsGuitarIdRouteImport } from './routes/example.guitars/$guitarId'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo.start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo.start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo.form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo.form.address'
import { Route as AdminCoreConfiguracoesRouteImport } from './routes/admin/core/configuracoes'
import { Route as AdminRhFuncionariosIndexRouteImport } from './routes/admin/rh/funcionarios/index'
import { Route as AdminRhEquipesIndexRouteImport } from './routes/admin/rh/equipes/index'
import { Route as AdminRhDepartamentosIndexRouteImport } from './routes/admin/rh/departamentos/index'
import { Route as AdminRhAvaliacoesExperienciaIndexRouteImport } from './routes/admin/rh/avaliacoes-experiencia/index'
import { Route as AdminCoreUsersIndexRouteImport } from './routes/admin/core/users/index'
import { Route as AdminCoreUnidadesIndexRouteImport } from './routes/admin/core/unidades/index'
import { Route as AdminCoreEmpresasIndexRouteImport } from './routes/admin/core/empresas/index'
import { Route as AdminAlmoxarifadoSolicitacoesIndexRouteImport } from './routes/admin/almoxarifado/solicitacoes/index'
import { Route as AdminAlmoxarifadoMateriaisIndexRouteImport } from './routes/admin/almoxarifado/materiais/index'
import { Route as AdminRhDepartamentosNovoRouteImport } from './routes/admin/rh/departamentos/novo'
import { Route as AdminRhDepartamentosIdRouteImport } from './routes/admin/rh/departamentos/$id'
import { Route as AdminCoreUsersNovoRouteImport } from './routes/admin/core/users/novo'
import { Route as AdminCoreUnidadesNovaRouteImport } from './routes/admin/core/unidades/nova'
import { Route as AdminCoreEmpresasNovaRouteImport } from './routes/admin/core/empresas/nova'
import { Route as AdminRhDepartamentosIdEditRouteImport } from './routes/admin/rh/departamentos/$id.edit'
import { Route as AdminCoreUsersIdEditRouteImport } from './routes/admin/core/users/$id.edit'
import { Route as AdminCoreUnidadesIdEditRouteImport } from './routes/admin/core/unidades/$id.edit'
import { Route as AdminCoreEmpresasIdEditRouteImport } from './routes/admin/core/empresas/$id.edit'
import { ServerRoute as ApiDemoTqTodosServerRouteImport } from './routes/api.demo-tq-todos'
import { ServerRoute as ApiDemoNamesServerRouteImport } from './routes/api.demo-names'
import { ServerRoute as ApiTrpcSplatServerRouteImport } from './routes/api.trpc.$'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTrpcTodoRoute = DemoTrpcTodoRouteImport.update({
  id: '/demo/trpc-todo',
  path: '/demo/trpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsIndexRoute = ExampleGuitarsIndexRouteImport.update({
  id: '/example/guitars/',
  path: '/example/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRhIndexRoute = AdminRhIndexRouteImport.update({
  id: '/admin/rh/',
  path: '/admin/rh/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreIndexRoute = AdminCoreIndexRouteImport.update({
  id: '/admin/core/',
  path: '/admin/core/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlmoxarifadoIndexRoute = AdminAlmoxarifadoIndexRouteImport.update({
  id: '/admin/almoxarifado/',
  path: '/admin/almoxarifado/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsGuitarIdRoute = ExampleGuitarsGuitarIdRouteImport.update({
  id: '/example/guitars/$guitarId',
  path: '/example/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreConfiguracoesRoute = AdminCoreConfiguracoesRouteImport.update({
  id: '/admin/core/configuracoes',
  path: '/admin/core/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRhFuncionariosIndexRoute =
  AdminRhFuncionariosIndexRouteImport.update({
    id: '/admin/rh/funcionarios/',
    path: '/admin/rh/funcionarios/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRhEquipesIndexRoute = AdminRhEquipesIndexRouteImport.update({
  id: '/admin/rh/equipes/',
  path: '/admin/rh/equipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRhDepartamentosIndexRoute =
  AdminRhDepartamentosIndexRouteImport.update({
    id: '/admin/rh/departamentos/',
    path: '/admin/rh/departamentos/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRhAvaliacoesExperienciaIndexRoute =
  AdminRhAvaliacoesExperienciaIndexRouteImport.update({
    id: '/admin/rh/avaliacoes-experiencia/',
    path: '/admin/rh/avaliacoes-experiencia/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCoreUsersIndexRoute = AdminCoreUsersIndexRouteImport.update({
  id: '/admin/core/users/',
  path: '/admin/core/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreUnidadesIndexRoute = AdminCoreUnidadesIndexRouteImport.update({
  id: '/admin/core/unidades/',
  path: '/admin/core/unidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreEmpresasIndexRoute = AdminCoreEmpresasIndexRouteImport.update({
  id: '/admin/core/empresas/',
  path: '/admin/core/empresas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlmoxarifadoSolicitacoesIndexRoute =
  AdminAlmoxarifadoSolicitacoesIndexRouteImport.update({
    id: '/admin/almoxarifado/solicitacoes/',
    path: '/admin/almoxarifado/solicitacoes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAlmoxarifadoMateriaisIndexRoute =
  AdminAlmoxarifadoMateriaisIndexRouteImport.update({
    id: '/admin/almoxarifado/materiais/',
    path: '/admin/almoxarifado/materiais/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRhDepartamentosNovoRoute =
  AdminRhDepartamentosNovoRouteImport.update({
    id: '/admin/rh/departamentos/novo',
    path: '/admin/rh/departamentos/novo',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRhDepartamentosIdRoute = AdminRhDepartamentosIdRouteImport.update({
  id: '/admin/rh/departamentos/$id',
  path: '/admin/rh/departamentos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreUsersNovoRoute = AdminCoreUsersNovoRouteImport.update({
  id: '/admin/core/users/novo',
  path: '/admin/core/users/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreUnidadesNovaRoute = AdminCoreUnidadesNovaRouteImport.update({
  id: '/admin/core/unidades/nova',
  path: '/admin/core/unidades/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreEmpresasNovaRoute = AdminCoreEmpresasNovaRouteImport.update({
  id: '/admin/core/empresas/nova',
  path: '/admin/core/empresas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRhDepartamentosIdEditRoute =
  AdminRhDepartamentosIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminRhDepartamentosIdRoute,
  } as any)
const AdminCoreUsersIdEditRoute = AdminCoreUsersIdEditRouteImport.update({
  id: '/admin/core/users/$id/edit',
  path: '/admin/core/users/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreUnidadesIdEditRoute = AdminCoreUnidadesIdEditRouteImport.update({
  id: '/admin/core/unidades/$id/edit',
  path: '/admin/core/unidades/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreEmpresasIdEditRoute = AdminCoreEmpresasIdEditRouteImport.update({
  id: '/admin/core/empresas/$id/edit',
  path: '/admin/core/empresas/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoTqTodosServerRoute = ApiDemoTqTodosServerRouteImport.update({
  id: '/api/demo-tq-todos',
  path: '/api/demo-tq-todos',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiDemoNamesServerRoute = ApiDemoNamesServerRouteImport.update({
  id: '/api/demo-names',
  path: '/api/demo-names',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiTrpcSplatServerRoute = ApiTrpcSplatServerRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/admin': typeof AdminIndexRoute
  '/admin/core/configuracoes': typeof AdminCoreConfiguracoesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/admin/almoxarifado': typeof AdminAlmoxarifadoIndexRoute
  '/admin/core': typeof AdminCoreIndexRoute
  '/admin/rh': typeof AdminRhIndexRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
  '/admin/core/empresas/nova': typeof AdminCoreEmpresasNovaRoute
  '/admin/core/unidades/nova': typeof AdminCoreUnidadesNovaRoute
  '/admin/core/users/novo': typeof AdminCoreUsersNovoRoute
  '/admin/rh/departamentos/$id': typeof AdminRhDepartamentosIdRouteWithChildren
  '/admin/rh/departamentos/novo': typeof AdminRhDepartamentosNovoRoute
  '/admin/almoxarifado/materiais': typeof AdminAlmoxarifadoMateriaisIndexRoute
  '/admin/almoxarifado/solicitacoes': typeof AdminAlmoxarifadoSolicitacoesIndexRoute
  '/admin/core/empresas': typeof AdminCoreEmpresasIndexRoute
  '/admin/core/unidades': typeof AdminCoreUnidadesIndexRoute
  '/admin/core/users': typeof AdminCoreUsersIndexRoute
  '/admin/rh/avaliacoes-experiencia': typeof AdminRhAvaliacoesExperienciaIndexRoute
  '/admin/rh/departamentos': typeof AdminRhDepartamentosIndexRoute
  '/admin/rh/equipes': typeof AdminRhEquipesIndexRoute
  '/admin/rh/funcionarios': typeof AdminRhFuncionariosIndexRoute
  '/admin/core/empresas/$id/edit': typeof AdminCoreEmpresasIdEditRoute
  '/admin/core/unidades/$id/edit': typeof AdminCoreUnidadesIdEditRoute
  '/admin/core/users/$id/edit': typeof AdminCoreUsersIdEditRoute
  '/admin/rh/departamentos/$id/edit': typeof AdminRhDepartamentosIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/admin': typeof AdminIndexRoute
  '/admin/core/configuracoes': typeof AdminCoreConfiguracoesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/admin/almoxarifado': typeof AdminAlmoxarifadoIndexRoute
  '/admin/core': typeof AdminCoreIndexRoute
  '/admin/rh': typeof AdminRhIndexRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
  '/admin/core/empresas/nova': typeof AdminCoreEmpresasNovaRoute
  '/admin/core/unidades/nova': typeof AdminCoreUnidadesNovaRoute
  '/admin/core/users/novo': typeof AdminCoreUsersNovoRoute
  '/admin/rh/departamentos/$id': typeof AdminRhDepartamentosIdRouteWithChildren
  '/admin/rh/departamentos/novo': typeof AdminRhDepartamentosNovoRoute
  '/admin/almoxarifado/materiais': typeof AdminAlmoxarifadoMateriaisIndexRoute
  '/admin/almoxarifado/solicitacoes': typeof AdminAlmoxarifadoSolicitacoesIndexRoute
  '/admin/core/empresas': typeof AdminCoreEmpresasIndexRoute
  '/admin/core/unidades': typeof AdminCoreUnidadesIndexRoute
  '/admin/core/users': typeof AdminCoreUsersIndexRoute
  '/admin/rh/avaliacoes-experiencia': typeof AdminRhAvaliacoesExperienciaIndexRoute
  '/admin/rh/departamentos': typeof AdminRhDepartamentosIndexRoute
  '/admin/rh/equipes': typeof AdminRhEquipesIndexRoute
  '/admin/rh/funcionarios': typeof AdminRhFuncionariosIndexRoute
  '/admin/core/empresas/$id/edit': typeof AdminCoreEmpresasIdEditRoute
  '/admin/core/unidades/$id/edit': typeof AdminCoreUnidadesIdEditRoute
  '/admin/core/users/$id/edit': typeof AdminCoreUsersIdEditRoute
  '/admin/rh/departamentos/$id/edit': typeof AdminRhDepartamentosIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth/login': typeof AuthLoginRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/core/configuracoes': typeof AdminCoreConfiguracoesRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/admin/almoxarifado/': typeof AdminAlmoxarifadoIndexRoute
  '/admin/core/': typeof AdminCoreIndexRoute
  '/admin/rh/': typeof AdminRhIndexRoute
  '/example/guitars/': typeof ExampleGuitarsIndexRoute
  '/admin/core/empresas/nova': typeof AdminCoreEmpresasNovaRoute
  '/admin/core/unidades/nova': typeof AdminCoreUnidadesNovaRoute
  '/admin/core/users/novo': typeof AdminCoreUsersNovoRoute
  '/admin/rh/departamentos/$id': typeof AdminRhDepartamentosIdRouteWithChildren
  '/admin/rh/departamentos/novo': typeof AdminRhDepartamentosNovoRoute
  '/admin/almoxarifado/materiais/': typeof AdminAlmoxarifadoMateriaisIndexRoute
  '/admin/almoxarifado/solicitacoes/': typeof AdminAlmoxarifadoSolicitacoesIndexRoute
  '/admin/core/empresas/': typeof AdminCoreEmpresasIndexRoute
  '/admin/core/unidades/': typeof AdminCoreUnidadesIndexRoute
  '/admin/core/users/': typeof AdminCoreUsersIndexRoute
  '/admin/rh/avaliacoes-experiencia/': typeof AdminRhAvaliacoesExperienciaIndexRoute
  '/admin/rh/departamentos/': typeof AdminRhDepartamentosIndexRoute
  '/admin/rh/equipes/': typeof AdminRhEquipesIndexRoute
  '/admin/rh/funcionarios/': typeof AdminRhFuncionariosIndexRoute
  '/admin/core/empresas/$id/edit': typeof AdminCoreEmpresasIdEditRoute
  '/admin/core/unidades/$id/edit': typeof AdminCoreUnidadesIdEditRoute
  '/admin/core/users/$id/edit': typeof AdminCoreUsersIdEditRoute
  '/admin/rh/departamentos/$id/edit': typeof AdminRhDepartamentosIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/admin'
    | '/admin/core/configuracoes'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/admin/almoxarifado'
    | '/admin/core'
    | '/admin/rh'
    | '/example/guitars'
    | '/admin/core/empresas/nova'
    | '/admin/core/unidades/nova'
    | '/admin/core/users/novo'
    | '/admin/rh/departamentos/$id'
    | '/admin/rh/departamentos/novo'
    | '/admin/almoxarifado/materiais'
    | '/admin/almoxarifado/solicitacoes'
    | '/admin/core/empresas'
    | '/admin/core/unidades'
    | '/admin/core/users'
    | '/admin/rh/avaliacoes-experiencia'
    | '/admin/rh/departamentos'
    | '/admin/rh/equipes'
    | '/admin/rh/funcionarios'
    | '/admin/core/empresas/$id/edit'
    | '/admin/core/unidades/$id/edit'
    | '/admin/core/users/$id/edit'
    | '/admin/rh/departamentos/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/admin'
    | '/admin/core/configuracoes'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/admin/almoxarifado'
    | '/admin/core'
    | '/admin/rh'
    | '/example/guitars'
    | '/admin/core/empresas/nova'
    | '/admin/core/unidades/nova'
    | '/admin/core/users/novo'
    | '/admin/rh/departamentos/$id'
    | '/admin/rh/departamentos/novo'
    | '/admin/almoxarifado/materiais'
    | '/admin/almoxarifado/solicitacoes'
    | '/admin/core/empresas'
    | '/admin/core/unidades'
    | '/admin/core/users'
    | '/admin/rh/avaliacoes-experiencia'
    | '/admin/rh/departamentos'
    | '/admin/rh/equipes'
    | '/admin/rh/funcionarios'
    | '/admin/core/empresas/$id/edit'
    | '/admin/core/unidades/$id/edit'
    | '/admin/core/users/$id/edit'
    | '/admin/rh/departamentos/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth/login'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/admin/'
    | '/admin/core/configuracoes'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/admin/almoxarifado/'
    | '/admin/core/'
    | '/admin/rh/'
    | '/example/guitars/'
    | '/admin/core/empresas/nova'
    | '/admin/core/unidades/nova'
    | '/admin/core/users/novo'
    | '/admin/rh/departamentos/$id'
    | '/admin/rh/departamentos/novo'
    | '/admin/almoxarifado/materiais/'
    | '/admin/almoxarifado/solicitacoes/'
    | '/admin/core/empresas/'
    | '/admin/core/unidades/'
    | '/admin/core/users/'
    | '/admin/rh/avaliacoes-experiencia/'
    | '/admin/rh/departamentos/'
    | '/admin/rh/equipes/'
    | '/admin/rh/funcionarios/'
    | '/admin/core/empresas/$id/edit'
    | '/admin/core/unidades/$id/edit'
    | '/admin/core/users/$id/edit'
    | '/admin/rh/departamentos/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoTrpcTodoRoute: typeof DemoTrpcTodoRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoreConfiguracoesRoute: typeof AdminCoreConfiguracoesRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ExampleGuitarsGuitarIdRoute: typeof ExampleGuitarsGuitarIdRoute
  AdminAlmoxarifadoIndexRoute: typeof AdminAlmoxarifadoIndexRoute
  AdminCoreIndexRoute: typeof AdminCoreIndexRoute
  AdminRhIndexRoute: typeof AdminRhIndexRoute
  ExampleGuitarsIndexRoute: typeof ExampleGuitarsIndexRoute
  AdminCoreEmpresasNovaRoute: typeof AdminCoreEmpresasNovaRoute
  AdminCoreUnidadesNovaRoute: typeof AdminCoreUnidadesNovaRoute
  AdminCoreUsersNovoRoute: typeof AdminCoreUsersNovoRoute
  AdminRhDepartamentosIdRoute: typeof AdminRhDepartamentosIdRouteWithChildren
  AdminRhDepartamentosNovoRoute: typeof AdminRhDepartamentosNovoRoute
  AdminAlmoxarifadoMateriaisIndexRoute: typeof AdminAlmoxarifadoMateriaisIndexRoute
  AdminAlmoxarifadoSolicitacoesIndexRoute: typeof AdminAlmoxarifadoSolicitacoesIndexRoute
  AdminCoreEmpresasIndexRoute: typeof AdminCoreEmpresasIndexRoute
  AdminCoreUnidadesIndexRoute: typeof AdminCoreUnidadesIndexRoute
  AdminCoreUsersIndexRoute: typeof AdminCoreUsersIndexRoute
  AdminRhAvaliacoesExperienciaIndexRoute: typeof AdminRhAvaliacoesExperienciaIndexRoute
  AdminRhDepartamentosIndexRoute: typeof AdminRhDepartamentosIndexRoute
  AdminRhEquipesIndexRoute: typeof AdminRhEquipesIndexRoute
  AdminRhFuncionariosIndexRoute: typeof AdminRhFuncionariosIndexRoute
  AdminCoreEmpresasIdEditRoute: typeof AdminCoreEmpresasIdEditRoute
  AdminCoreUnidadesIdEditRoute: typeof AdminCoreUnidadesIdEditRoute
  AdminCoreUsersIdEditRoute: typeof AdminCoreUsersIdEditRoute
}
export interface FileServerRoutesByFullPath {
  '/api/demo-names': typeof ApiDemoNamesServerRoute
  '/api/demo-tq-todos': typeof ApiDemoTqTodosServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/demo-names': typeof ApiDemoNamesServerRoute
  '/api/demo-tq-todos': typeof ApiDemoTqTodosServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/demo-names': typeof ApiDemoNamesServerRoute
  '/api/demo-tq-todos': typeof ApiDemoTqTodosServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/demo-names' | '/api/demo-tq-todos' | '/api/trpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/demo-names' | '/api/demo-tq-todos' | '/api/trpc/$'
  id: '__root__' | '/api/demo-names' | '/api/demo-tq-todos' | '/api/trpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiDemoNamesServerRoute: typeof ApiDemoNamesServerRoute
  ApiDemoTqTodosServerRoute: typeof ApiDemoTqTodosServerRoute
  ApiTrpcSplatServerRoute: typeof ApiTrpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/trpc-todo': {
      id: '/demo/trpc-todo'
      path: '/demo/trpc-todo'
      fullPath: '/demo/trpc-todo'
      preLoaderRoute: typeof DemoTrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/': {
      id: '/example/guitars/'
      path: '/example/guitars'
      fullPath: '/example/guitars'
      preLoaderRoute: typeof ExampleGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/': {
      id: '/admin/rh/'
      path: '/admin/rh'
      fullPath: '/admin/rh'
      preLoaderRoute: typeof AdminRhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/': {
      id: '/admin/core/'
      path: '/admin/core'
      fullPath: '/admin/core'
      preLoaderRoute: typeof AdminCoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/almoxarifado/': {
      id: '/admin/almoxarifado/'
      path: '/admin/almoxarifado'
      fullPath: '/admin/almoxarifado'
      preLoaderRoute: typeof AdminAlmoxarifadoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/$guitarId': {
      id: '/example/guitars/$guitarId'
      path: '/example/guitars/$guitarId'
      fullPath: '/example/guitars/$guitarId'
      preLoaderRoute: typeof ExampleGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/configuracoes': {
      id: '/admin/core/configuracoes'
      path: '/admin/core/configuracoes'
      fullPath: '/admin/core/configuracoes'
      preLoaderRoute: typeof AdminCoreConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/funcionarios/': {
      id: '/admin/rh/funcionarios/'
      path: '/admin/rh/funcionarios'
      fullPath: '/admin/rh/funcionarios'
      preLoaderRoute: typeof AdminRhFuncionariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/equipes/': {
      id: '/admin/rh/equipes/'
      path: '/admin/rh/equipes'
      fullPath: '/admin/rh/equipes'
      preLoaderRoute: typeof AdminRhEquipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/departamentos/': {
      id: '/admin/rh/departamentos/'
      path: '/admin/rh/departamentos'
      fullPath: '/admin/rh/departamentos'
      preLoaderRoute: typeof AdminRhDepartamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/avaliacoes-experiencia/': {
      id: '/admin/rh/avaliacoes-experiencia/'
      path: '/admin/rh/avaliacoes-experiencia'
      fullPath: '/admin/rh/avaliacoes-experiencia'
      preLoaderRoute: typeof AdminRhAvaliacoesExperienciaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/users/': {
      id: '/admin/core/users/'
      path: '/admin/core/users'
      fullPath: '/admin/core/users'
      preLoaderRoute: typeof AdminCoreUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/unidades/': {
      id: '/admin/core/unidades/'
      path: '/admin/core/unidades'
      fullPath: '/admin/core/unidades'
      preLoaderRoute: typeof AdminCoreUnidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/empresas/': {
      id: '/admin/core/empresas/'
      path: '/admin/core/empresas'
      fullPath: '/admin/core/empresas'
      preLoaderRoute: typeof AdminCoreEmpresasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/almoxarifado/solicitacoes/': {
      id: '/admin/almoxarifado/solicitacoes/'
      path: '/admin/almoxarifado/solicitacoes'
      fullPath: '/admin/almoxarifado/solicitacoes'
      preLoaderRoute: typeof AdminAlmoxarifadoSolicitacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/almoxarifado/materiais/': {
      id: '/admin/almoxarifado/materiais/'
      path: '/admin/almoxarifado/materiais'
      fullPath: '/admin/almoxarifado/materiais'
      preLoaderRoute: typeof AdminAlmoxarifadoMateriaisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/departamentos/novo': {
      id: '/admin/rh/departamentos/novo'
      path: '/admin/rh/departamentos/novo'
      fullPath: '/admin/rh/departamentos/novo'
      preLoaderRoute: typeof AdminRhDepartamentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/departamentos/$id': {
      id: '/admin/rh/departamentos/$id'
      path: '/admin/rh/departamentos/$id'
      fullPath: '/admin/rh/departamentos/$id'
      preLoaderRoute: typeof AdminRhDepartamentosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/users/novo': {
      id: '/admin/core/users/novo'
      path: '/admin/core/users/novo'
      fullPath: '/admin/core/users/novo'
      preLoaderRoute: typeof AdminCoreUsersNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/unidades/nova': {
      id: '/admin/core/unidades/nova'
      path: '/admin/core/unidades/nova'
      fullPath: '/admin/core/unidades/nova'
      preLoaderRoute: typeof AdminCoreUnidadesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/empresas/nova': {
      id: '/admin/core/empresas/nova'
      path: '/admin/core/empresas/nova'
      fullPath: '/admin/core/empresas/nova'
      preLoaderRoute: typeof AdminCoreEmpresasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/departamentos/$id/edit': {
      id: '/admin/rh/departamentos/$id/edit'
      path: '/edit'
      fullPath: '/admin/rh/departamentos/$id/edit'
      preLoaderRoute: typeof AdminRhDepartamentosIdEditRouteImport
      parentRoute: typeof AdminRhDepartamentosIdRoute
    }
    '/admin/core/users/$id/edit': {
      id: '/admin/core/users/$id/edit'
      path: '/admin/core/users/$id/edit'
      fullPath: '/admin/core/users/$id/edit'
      preLoaderRoute: typeof AdminCoreUsersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/unidades/$id/edit': {
      id: '/admin/core/unidades/$id/edit'
      path: '/admin/core/unidades/$id/edit'
      fullPath: '/admin/core/unidades/$id/edit'
      preLoaderRoute: typeof AdminCoreUnidadesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/empresas/$id/edit': {
      id: '/admin/core/empresas/$id/edit'
      path: '/admin/core/empresas/$id/edit'
      fullPath: '/admin/core/empresas/$id/edit'
      preLoaderRoute: typeof AdminCoreEmpresasIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/demo-tq-todos': {
      id: '/api/demo-tq-todos'
      path: '/api/demo-tq-todos'
      fullPath: '/api/demo-tq-todos'
      preLoaderRoute: typeof ApiDemoTqTodosServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/demo-names': {
      id: '/api/demo-names'
      path: '/api/demo-names'
      fullPath: '/api/demo-names'
      preLoaderRoute: typeof ApiDemoNamesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AdminRhDepartamentosIdRouteChildren {
  AdminRhDepartamentosIdEditRoute: typeof AdminRhDepartamentosIdEditRoute
}

const AdminRhDepartamentosIdRouteChildren: AdminRhDepartamentosIdRouteChildren =
  {
    AdminRhDepartamentosIdEditRoute: AdminRhDepartamentosIdEditRoute,
  }

const AdminRhDepartamentosIdRouteWithChildren =
  AdminRhDepartamentosIdRoute._addFileChildren(
    AdminRhDepartamentosIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoTrpcTodoRoute: DemoTrpcTodoRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCoreConfiguracoesRoute: AdminCoreConfiguracoesRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ExampleGuitarsGuitarIdRoute: ExampleGuitarsGuitarIdRoute,
  AdminAlmoxarifadoIndexRoute: AdminAlmoxarifadoIndexRoute,
  AdminCoreIndexRoute: AdminCoreIndexRoute,
  AdminRhIndexRoute: AdminRhIndexRoute,
  ExampleGuitarsIndexRoute: ExampleGuitarsIndexRoute,
  AdminCoreEmpresasNovaRoute: AdminCoreEmpresasNovaRoute,
  AdminCoreUnidadesNovaRoute: AdminCoreUnidadesNovaRoute,
  AdminCoreUsersNovoRoute: AdminCoreUsersNovoRoute,
  AdminRhDepartamentosIdRoute: AdminRhDepartamentosIdRouteWithChildren,
  AdminRhDepartamentosNovoRoute: AdminRhDepartamentosNovoRoute,
  AdminAlmoxarifadoMateriaisIndexRoute: AdminAlmoxarifadoMateriaisIndexRoute,
  AdminAlmoxarifadoSolicitacoesIndexRoute:
    AdminAlmoxarifadoSolicitacoesIndexRoute,
  AdminCoreEmpresasIndexRoute: AdminCoreEmpresasIndexRoute,
  AdminCoreUnidadesIndexRoute: AdminCoreUnidadesIndexRoute,
  AdminCoreUsersIndexRoute: AdminCoreUsersIndexRoute,
  AdminRhAvaliacoesExperienciaIndexRoute:
    AdminRhAvaliacoesExperienciaIndexRoute,
  AdminRhDepartamentosIndexRoute: AdminRhDepartamentosIndexRoute,
  AdminRhEquipesIndexRoute: AdminRhEquipesIndexRoute,
  AdminRhFuncionariosIndexRoute: AdminRhFuncionariosIndexRoute,
  AdminCoreEmpresasIdEditRoute: AdminCoreEmpresasIdEditRoute,
  AdminCoreUnidadesIdEditRoute: AdminCoreUnidadesIdEditRoute,
  AdminCoreUsersIdEditRoute: AdminCoreUsersIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiDemoNamesServerRoute: ApiDemoNamesServerRoute,
  ApiDemoTqTodosServerRoute: ApiDemoTqTodosServerRoute,
  ApiTrpcSplatServerRoute: ApiTrpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
