/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AdminRhIndexRouteImport } from './routes/admin/rh/index'
import { Route as AdminCoreIndexRouteImport } from './routes/admin/core/index'
import { Route as AdminChecklistIndexRouteImport } from './routes/admin/checklist/index'
import { Route as AdminAlmoxarifadoIndexRouteImport } from './routes/admin/almoxarifado/index'
import { Route as AdminUserProfileRouteImport } from './routes/admin/user/profile'
import { Route as AdminUserAlterarSenhaRouteImport } from './routes/admin/user/alterar-senha'
import { Route as AdminCoreConfiguracoesRouteImport } from './routes/admin/core/configuracoes'
import { Route as AdminRhImportacaoPontowebIndexRouteImport } from './routes/admin/rh/importacao-pontoweb/index'
import { Route as AdminRhFuncionariosIndexRouteImport } from './routes/admin/rh/funcionarios/index'
import { Route as AdminRhEquipesIndexRouteImport } from './routes/admin/rh/equipes/index'
import { Route as AdminRhDepartamentosIndexRouteImport } from './routes/admin/rh/departamentos/index'
import { Route as AdminRhCargosIndexRouteImport } from './routes/admin/rh/cargos/index'
import { Route as AdminRhAvaliacoesExperienciaIndexRouteImport } from './routes/admin/rh/avaliacoes-experiencia/index'
import { Route as AdminCoreUsersIndexRouteImport } from './routes/admin/core/users/index'
import { Route as AdminCoreUnidadesIndexRouteImport } from './routes/admin/core/unidades/index'
import { Route as AdminCoreEmpresasIndexRouteImport } from './routes/admin/core/empresas/index'
import { Route as AdminChecklistTemplatesIndexRouteImport } from './routes/admin/checklist/templates/index'
import { Route as AdminChecklistRelatoriosIndexRouteImport } from './routes/admin/checklist/relatorios/index'
import { Route as AdminChecklistAvaliacoesIndexRouteImport } from './routes/admin/checklist/avaliacoes/index'
import { Route as AdminAlmoxarifadoSolicitacoesIndexRouteImport } from './routes/admin/almoxarifado/solicitacoes/index'
import { Route as AdminAlmoxarifadoRelatoriosIndexRouteImport } from './routes/admin/almoxarifado/relatorios/index'
import { Route as AdminAlmoxarifadoMateriaisIndexRouteImport } from './routes/admin/almoxarifado/materiais/index'
import { Route as AdminRhDepartamentosNovoRouteImport } from './routes/admin/rh/departamentos/novo'
import { Route as AdminRhCargosNovoRouteImport } from './routes/admin/rh/cargos/novo'
import { Route as AdminCoreUsersNovoRouteImport } from './routes/admin/core/users/novo'
import { Route as AdminCoreUnidadesNovaRouteImport } from './routes/admin/core/unidades/nova'
import { Route as AdminCoreEmpresasNovaRouteImport } from './routes/admin/core/empresas/nova'
import { Route as AdminChecklistTemplatesNovoRouteImport } from './routes/admin/checklist/templates/novo'
import { Route as AdminAlmoxarifadoSolicitacoesNovaRouteImport } from './routes/admin/almoxarifado/solicitacoes/nova'
import { Route as AdminAlmoxarifadoMateriaisNovoRouteImport } from './routes/admin/almoxarifado/materiais/novo'
import { Route as AdminCoreUsersIndexOldRouteImport } from './routes/admin/core/users/index.old'
import { Route as AdminCoreUnidadesIndexOldRouteImport } from './routes/admin/core/unidades/index.old'
import { Route as AdminCoreEmpresasIndexOldRouteImport } from './routes/admin/core/empresas/index.old'
import { Route as AdminAlmoxarifadoSolicitacoesIndexOldRouteImport } from './routes/admin/almoxarifado/solicitacoes/index.old'
import { Route as AdminAlmoxarifadoMateriaisIndexOldRouteImport } from './routes/admin/almoxarifado/materiais/index.old'
import { Route as AdminRhDepartamentosIdIndexRouteImport } from './routes/admin/rh/departamentos/$id/index'
import { Route as AdminAlmoxarifadoSolicitacoesIdIndexRouteImport } from './routes/admin/almoxarifado/solicitacoes/$id/index'
import { Route as AdminRhDepartamentosIdEditRouteImport } from './routes/admin/rh/departamentos/$id/edit'
import { Route as AdminRhCargosIdEditRouteImport } from './routes/admin/rh/cargos/$id.edit'
import { Route as AdminCoreUsersIdEditRouteImport } from './routes/admin/core/users/$id/edit'
import { Route as AdminCoreUnidadesIdEditRouteImport } from './routes/admin/core/unidades/$id.edit'
import { Route as AdminCoreEmpresasIdEditRouteImport } from './routes/admin/core/empresas/$id.edit'
import { Route as AdminAlmoxarifadoSolicitacoesIdPrintRouteImport } from './routes/admin/almoxarifado/solicitacoes/$id/print'
import { Route as AdminAlmoxarifadoMateriaisIdEditRouteImport } from './routes/admin/almoxarifado/materiais/$id.edit'
import { ServerRoute as ApiUploadServerRouteImport } from './routes/api/upload'
import { ServerRoute as ApiTrpcSplatServerRouteImport } from './routes/api/trpc.$'
import { ServerRoute as ApiImagesSplatServerRouteImport } from './routes/api/images.$'

const rootServerRouteImport = createServerRootRoute()

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRhIndexRoute = AdminRhIndexRouteImport.update({
  id: '/admin/rh/',
  path: '/admin/rh/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreIndexRoute = AdminCoreIndexRouteImport.update({
  id: '/admin/core/',
  path: '/admin/core/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChecklistIndexRoute = AdminChecklistIndexRouteImport.update({
  id: '/admin/checklist/',
  path: '/admin/checklist/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlmoxarifadoIndexRoute = AdminAlmoxarifadoIndexRouteImport.update({
  id: '/admin/almoxarifado/',
  path: '/admin/almoxarifado/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserProfileRoute = AdminUserProfileRouteImport.update({
  id: '/admin/user/profile',
  path: '/admin/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserAlterarSenhaRoute = AdminUserAlterarSenhaRouteImport.update({
  id: '/admin/user/alterar-senha',
  path: '/admin/user/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreConfiguracoesRoute = AdminCoreConfiguracoesRouteImport.update({
  id: '/admin/core/configuracoes',
  path: '/admin/core/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRhImportacaoPontowebIndexRoute =
  AdminRhImportacaoPontowebIndexRouteImport.update({
    id: '/admin/rh/importacao-pontoweb/',
    path: '/admin/rh/importacao-pontoweb/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRhFuncionariosIndexRoute =
  AdminRhFuncionariosIndexRouteImport.update({
    id: '/admin/rh/funcionarios/',
    path: '/admin/rh/funcionarios/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRhEquipesIndexRoute = AdminRhEquipesIndexRouteImport.update({
  id: '/admin/rh/equipes/',
  path: '/admin/rh/equipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRhDepartamentosIndexRoute =
  AdminRhDepartamentosIndexRouteImport.update({
    id: '/admin/rh/departamentos/',
    path: '/admin/rh/departamentos/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRhCargosIndexRoute = AdminRhCargosIndexRouteImport.update({
  id: '/admin/rh/cargos/',
  path: '/admin/rh/cargos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRhAvaliacoesExperienciaIndexRoute =
  AdminRhAvaliacoesExperienciaIndexRouteImport.update({
    id: '/admin/rh/avaliacoes-experiencia/',
    path: '/admin/rh/avaliacoes-experiencia/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCoreUsersIndexRoute = AdminCoreUsersIndexRouteImport.update({
  id: '/admin/core/users/',
  path: '/admin/core/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreUnidadesIndexRoute = AdminCoreUnidadesIndexRouteImport.update({
  id: '/admin/core/unidades/',
  path: '/admin/core/unidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreEmpresasIndexRoute = AdminCoreEmpresasIndexRouteImport.update({
  id: '/admin/core/empresas/',
  path: '/admin/core/empresas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChecklistTemplatesIndexRoute =
  AdminChecklistTemplatesIndexRouteImport.update({
    id: '/admin/checklist/templates/',
    path: '/admin/checklist/templates/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminChecklistRelatoriosIndexRoute =
  AdminChecklistRelatoriosIndexRouteImport.update({
    id: '/admin/checklist/relatorios/',
    path: '/admin/checklist/relatorios/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminChecklistAvaliacoesIndexRoute =
  AdminChecklistAvaliacoesIndexRouteImport.update({
    id: '/admin/checklist/avaliacoes/',
    path: '/admin/checklist/avaliacoes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAlmoxarifadoSolicitacoesIndexRoute =
  AdminAlmoxarifadoSolicitacoesIndexRouteImport.update({
    id: '/admin/almoxarifado/solicitacoes/',
    path: '/admin/almoxarifado/solicitacoes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAlmoxarifadoRelatoriosIndexRoute =
  AdminAlmoxarifadoRelatoriosIndexRouteImport.update({
    id: '/admin/almoxarifado/relatorios/',
    path: '/admin/almoxarifado/relatorios/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAlmoxarifadoMateriaisIndexRoute =
  AdminAlmoxarifadoMateriaisIndexRouteImport.update({
    id: '/admin/almoxarifado/materiais/',
    path: '/admin/almoxarifado/materiais/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRhDepartamentosNovoRoute =
  AdminRhDepartamentosNovoRouteImport.update({
    id: '/admin/rh/departamentos/novo',
    path: '/admin/rh/departamentos/novo',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRhCargosNovoRoute = AdminRhCargosNovoRouteImport.update({
  id: '/admin/rh/cargos/novo',
  path: '/admin/rh/cargos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreUsersNovoRoute = AdminCoreUsersNovoRouteImport.update({
  id: '/admin/core/users/novo',
  path: '/admin/core/users/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreUnidadesNovaRoute = AdminCoreUnidadesNovaRouteImport.update({
  id: '/admin/core/unidades/nova',
  path: '/admin/core/unidades/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreEmpresasNovaRoute = AdminCoreEmpresasNovaRouteImport.update({
  id: '/admin/core/empresas/nova',
  path: '/admin/core/empresas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChecklistTemplatesNovoRoute =
  AdminChecklistTemplatesNovoRouteImport.update({
    id: '/admin/checklist/templates/novo',
    path: '/admin/checklist/templates/novo',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAlmoxarifadoSolicitacoesNovaRoute =
  AdminAlmoxarifadoSolicitacoesNovaRouteImport.update({
    id: '/admin/almoxarifado/solicitacoes/nova',
    path: '/admin/almoxarifado/solicitacoes/nova',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAlmoxarifadoMateriaisNovoRoute =
  AdminAlmoxarifadoMateriaisNovoRouteImport.update({
    id: '/admin/almoxarifado/materiais/novo',
    path: '/admin/almoxarifado/materiais/novo',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCoreUsersIndexOldRoute = AdminCoreUsersIndexOldRouteImport.update({
  id: '/admin/core/users/index/old',
  path: '/admin/core/users/index/old',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreUnidadesIndexOldRoute =
  AdminCoreUnidadesIndexOldRouteImport.update({
    id: '/admin/core/unidades/index/old',
    path: '/admin/core/unidades/index/old',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCoreEmpresasIndexOldRoute =
  AdminCoreEmpresasIndexOldRouteImport.update({
    id: '/admin/core/empresas/index/old',
    path: '/admin/core/empresas/index/old',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAlmoxarifadoSolicitacoesIndexOldRoute =
  AdminAlmoxarifadoSolicitacoesIndexOldRouteImport.update({
    id: '/admin/almoxarifado/solicitacoes/index/old',
    path: '/admin/almoxarifado/solicitacoes/index/old',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAlmoxarifadoMateriaisIndexOldRoute =
  AdminAlmoxarifadoMateriaisIndexOldRouteImport.update({
    id: '/admin/almoxarifado/materiais/index/old',
    path: '/admin/almoxarifado/materiais/index/old',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRhDepartamentosIdIndexRoute =
  AdminRhDepartamentosIdIndexRouteImport.update({
    id: '/admin/rh/departamentos/$id/',
    path: '/admin/rh/departamentos/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAlmoxarifadoSolicitacoesIdIndexRoute =
  AdminAlmoxarifadoSolicitacoesIdIndexRouteImport.update({
    id: '/admin/almoxarifado/solicitacoes/$id/',
    path: '/admin/almoxarifado/solicitacoes/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRhDepartamentosIdEditRoute =
  AdminRhDepartamentosIdEditRouteImport.update({
    id: '/admin/rh/departamentos/$id/edit',
    path: '/admin/rh/departamentos/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRhCargosIdEditRoute = AdminRhCargosIdEditRouteImport.update({
  id: '/admin/rh/cargos/$id/edit',
  path: '/admin/rh/cargos/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreUsersIdEditRoute = AdminCoreUsersIdEditRouteImport.update({
  id: '/admin/core/users/$id/edit',
  path: '/admin/core/users/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreUnidadesIdEditRoute = AdminCoreUnidadesIdEditRouteImport.update({
  id: '/admin/core/unidades/$id/edit',
  path: '/admin/core/unidades/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoreEmpresasIdEditRoute = AdminCoreEmpresasIdEditRouteImport.update({
  id: '/admin/core/empresas/$id/edit',
  path: '/admin/core/empresas/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlmoxarifadoSolicitacoesIdPrintRoute =
  AdminAlmoxarifadoSolicitacoesIdPrintRouteImport.update({
    id: '/admin/almoxarifado/solicitacoes/$id/print',
    path: '/admin/almoxarifado/solicitacoes/$id/print',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAlmoxarifadoMateriaisIdEditRoute =
  AdminAlmoxarifadoMateriaisIdEditRouteImport.update({
    id: '/admin/almoxarifado/materiais/$id/edit',
    path: '/admin/almoxarifado/materiais/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadServerRoute = ApiUploadServerRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiTrpcSplatServerRoute = ApiTrpcSplatServerRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiImagesSplatServerRoute = ApiImagesSplatServerRouteImport.update({
  id: '/api/images/$',
  path: '/api/images/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/superadmin': typeof SuperadminRoute
  '/login': typeof AuthLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/core/configuracoes': typeof AdminCoreConfiguracoesRoute
  '/admin/user/alterar-senha': typeof AdminUserAlterarSenhaRoute
  '/admin/user/profile': typeof AdminUserProfileRoute
  '/admin/almoxarifado': typeof AdminAlmoxarifadoIndexRoute
  '/admin/checklist': typeof AdminChecklistIndexRoute
  '/admin/core': typeof AdminCoreIndexRoute
  '/admin/rh': typeof AdminRhIndexRoute
  '/admin/almoxarifado/materiais/novo': typeof AdminAlmoxarifadoMateriaisNovoRoute
  '/admin/almoxarifado/solicitacoes/nova': typeof AdminAlmoxarifadoSolicitacoesNovaRoute
  '/admin/checklist/templates/novo': typeof AdminChecklistTemplatesNovoRoute
  '/admin/core/empresas/nova': typeof AdminCoreEmpresasNovaRoute
  '/admin/core/unidades/nova': typeof AdminCoreUnidadesNovaRoute
  '/admin/core/users/novo': typeof AdminCoreUsersNovoRoute
  '/admin/rh/cargos/novo': typeof AdminRhCargosNovoRoute
  '/admin/rh/departamentos/novo': typeof AdminRhDepartamentosNovoRoute
  '/admin/almoxarifado/materiais': typeof AdminAlmoxarifadoMateriaisIndexRoute
  '/admin/almoxarifado/relatorios': typeof AdminAlmoxarifadoRelatoriosIndexRoute
  '/admin/almoxarifado/solicitacoes': typeof AdminAlmoxarifadoSolicitacoesIndexRoute
  '/admin/checklist/avaliacoes': typeof AdminChecklistAvaliacoesIndexRoute
  '/admin/checklist/relatorios': typeof AdminChecklistRelatoriosIndexRoute
  '/admin/checklist/templates': typeof AdminChecklistTemplatesIndexRoute
  '/admin/core/empresas': typeof AdminCoreEmpresasIndexRoute
  '/admin/core/unidades': typeof AdminCoreUnidadesIndexRoute
  '/admin/core/users': typeof AdminCoreUsersIndexRoute
  '/admin/rh/avaliacoes-experiencia': typeof AdminRhAvaliacoesExperienciaIndexRoute
  '/admin/rh/cargos': typeof AdminRhCargosIndexRoute
  '/admin/rh/departamentos': typeof AdminRhDepartamentosIndexRoute
  '/admin/rh/equipes': typeof AdminRhEquipesIndexRoute
  '/admin/rh/funcionarios': typeof AdminRhFuncionariosIndexRoute
  '/admin/rh/importacao-pontoweb': typeof AdminRhImportacaoPontowebIndexRoute
  '/admin/almoxarifado/materiais/$id/edit': typeof AdminAlmoxarifadoMateriaisIdEditRoute
  '/admin/almoxarifado/solicitacoes/$id/print': typeof AdminAlmoxarifadoSolicitacoesIdPrintRoute
  '/admin/core/empresas/$id/edit': typeof AdminCoreEmpresasIdEditRoute
  '/admin/core/unidades/$id/edit': typeof AdminCoreUnidadesIdEditRoute
  '/admin/core/users/$id/edit': typeof AdminCoreUsersIdEditRoute
  '/admin/rh/cargos/$id/edit': typeof AdminRhCargosIdEditRoute
  '/admin/rh/departamentos/$id/edit': typeof AdminRhDepartamentosIdEditRoute
  '/admin/almoxarifado/solicitacoes/$id': typeof AdminAlmoxarifadoSolicitacoesIdIndexRoute
  '/admin/rh/departamentos/$id': typeof AdminRhDepartamentosIdIndexRoute
  '/admin/almoxarifado/materiais/index/old': typeof AdminAlmoxarifadoMateriaisIndexOldRoute
  '/admin/almoxarifado/solicitacoes/index/old': typeof AdminAlmoxarifadoSolicitacoesIndexOldRoute
  '/admin/core/empresas/index/old': typeof AdminCoreEmpresasIndexOldRoute
  '/admin/core/unidades/index/old': typeof AdminCoreUnidadesIndexOldRoute
  '/admin/core/users/index/old': typeof AdminCoreUsersIndexOldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/superadmin': typeof SuperadminRoute
  '/login': typeof AuthLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/core/configuracoes': typeof AdminCoreConfiguracoesRoute
  '/admin/user/alterar-senha': typeof AdminUserAlterarSenhaRoute
  '/admin/user/profile': typeof AdminUserProfileRoute
  '/admin/almoxarifado': typeof AdminAlmoxarifadoIndexRoute
  '/admin/checklist': typeof AdminChecklistIndexRoute
  '/admin/core': typeof AdminCoreIndexRoute
  '/admin/rh': typeof AdminRhIndexRoute
  '/admin/almoxarifado/materiais/novo': typeof AdminAlmoxarifadoMateriaisNovoRoute
  '/admin/almoxarifado/solicitacoes/nova': typeof AdminAlmoxarifadoSolicitacoesNovaRoute
  '/admin/checklist/templates/novo': typeof AdminChecklistTemplatesNovoRoute
  '/admin/core/empresas/nova': typeof AdminCoreEmpresasNovaRoute
  '/admin/core/unidades/nova': typeof AdminCoreUnidadesNovaRoute
  '/admin/core/users/novo': typeof AdminCoreUsersNovoRoute
  '/admin/rh/cargos/novo': typeof AdminRhCargosNovoRoute
  '/admin/rh/departamentos/novo': typeof AdminRhDepartamentosNovoRoute
  '/admin/almoxarifado/materiais': typeof AdminAlmoxarifadoMateriaisIndexRoute
  '/admin/almoxarifado/relatorios': typeof AdminAlmoxarifadoRelatoriosIndexRoute
  '/admin/almoxarifado/solicitacoes': typeof AdminAlmoxarifadoSolicitacoesIndexRoute
  '/admin/checklist/avaliacoes': typeof AdminChecklistAvaliacoesIndexRoute
  '/admin/checklist/relatorios': typeof AdminChecklistRelatoriosIndexRoute
  '/admin/checklist/templates': typeof AdminChecklistTemplatesIndexRoute
  '/admin/core/empresas': typeof AdminCoreEmpresasIndexRoute
  '/admin/core/unidades': typeof AdminCoreUnidadesIndexRoute
  '/admin/core/users': typeof AdminCoreUsersIndexRoute
  '/admin/rh/avaliacoes-experiencia': typeof AdminRhAvaliacoesExperienciaIndexRoute
  '/admin/rh/cargos': typeof AdminRhCargosIndexRoute
  '/admin/rh/departamentos': typeof AdminRhDepartamentosIndexRoute
  '/admin/rh/equipes': typeof AdminRhEquipesIndexRoute
  '/admin/rh/funcionarios': typeof AdminRhFuncionariosIndexRoute
  '/admin/rh/importacao-pontoweb': typeof AdminRhImportacaoPontowebIndexRoute
  '/admin/almoxarifado/materiais/$id/edit': typeof AdminAlmoxarifadoMateriaisIdEditRoute
  '/admin/almoxarifado/solicitacoes/$id/print': typeof AdminAlmoxarifadoSolicitacoesIdPrintRoute
  '/admin/core/empresas/$id/edit': typeof AdminCoreEmpresasIdEditRoute
  '/admin/core/unidades/$id/edit': typeof AdminCoreUnidadesIdEditRoute
  '/admin/core/users/$id/edit': typeof AdminCoreUsersIdEditRoute
  '/admin/rh/cargos/$id/edit': typeof AdminRhCargosIdEditRoute
  '/admin/rh/departamentos/$id/edit': typeof AdminRhDepartamentosIdEditRoute
  '/admin/almoxarifado/solicitacoes/$id': typeof AdminAlmoxarifadoSolicitacoesIdIndexRoute
  '/admin/rh/departamentos/$id': typeof AdminRhDepartamentosIdIndexRoute
  '/admin/almoxarifado/materiais/index/old': typeof AdminAlmoxarifadoMateriaisIndexOldRoute
  '/admin/almoxarifado/solicitacoes/index/old': typeof AdminAlmoxarifadoSolicitacoesIndexOldRoute
  '/admin/core/empresas/index/old': typeof AdminCoreEmpresasIndexOldRoute
  '/admin/core/unidades/index/old': typeof AdminCoreUnidadesIndexOldRoute
  '/admin/core/users/index/old': typeof AdminCoreUsersIndexOldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/superadmin': typeof SuperadminRoute
  '/_auth/login': typeof AuthLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/core/configuracoes': typeof AdminCoreConfiguracoesRoute
  '/admin/user/alterar-senha': typeof AdminUserAlterarSenhaRoute
  '/admin/user/profile': typeof AdminUserProfileRoute
  '/admin/almoxarifado/': typeof AdminAlmoxarifadoIndexRoute
  '/admin/checklist/': typeof AdminChecklistIndexRoute
  '/admin/core/': typeof AdminCoreIndexRoute
  '/admin/rh/': typeof AdminRhIndexRoute
  '/admin/almoxarifado/materiais/novo': typeof AdminAlmoxarifadoMateriaisNovoRoute
  '/admin/almoxarifado/solicitacoes/nova': typeof AdminAlmoxarifadoSolicitacoesNovaRoute
  '/admin/checklist/templates/novo': typeof AdminChecklistTemplatesNovoRoute
  '/admin/core/empresas/nova': typeof AdminCoreEmpresasNovaRoute
  '/admin/core/unidades/nova': typeof AdminCoreUnidadesNovaRoute
  '/admin/core/users/novo': typeof AdminCoreUsersNovoRoute
  '/admin/rh/cargos/novo': typeof AdminRhCargosNovoRoute
  '/admin/rh/departamentos/novo': typeof AdminRhDepartamentosNovoRoute
  '/admin/almoxarifado/materiais/': typeof AdminAlmoxarifadoMateriaisIndexRoute
  '/admin/almoxarifado/relatorios/': typeof AdminAlmoxarifadoRelatoriosIndexRoute
  '/admin/almoxarifado/solicitacoes/': typeof AdminAlmoxarifadoSolicitacoesIndexRoute
  '/admin/checklist/avaliacoes/': typeof AdminChecklistAvaliacoesIndexRoute
  '/admin/checklist/relatorios/': typeof AdminChecklistRelatoriosIndexRoute
  '/admin/checklist/templates/': typeof AdminChecklistTemplatesIndexRoute
  '/admin/core/empresas/': typeof AdminCoreEmpresasIndexRoute
  '/admin/core/unidades/': typeof AdminCoreUnidadesIndexRoute
  '/admin/core/users/': typeof AdminCoreUsersIndexRoute
  '/admin/rh/avaliacoes-experiencia/': typeof AdminRhAvaliacoesExperienciaIndexRoute
  '/admin/rh/cargos/': typeof AdminRhCargosIndexRoute
  '/admin/rh/departamentos/': typeof AdminRhDepartamentosIndexRoute
  '/admin/rh/equipes/': typeof AdminRhEquipesIndexRoute
  '/admin/rh/funcionarios/': typeof AdminRhFuncionariosIndexRoute
  '/admin/rh/importacao-pontoweb/': typeof AdminRhImportacaoPontowebIndexRoute
  '/admin/almoxarifado/materiais/$id/edit': typeof AdminAlmoxarifadoMateriaisIdEditRoute
  '/admin/almoxarifado/solicitacoes/$id/print': typeof AdminAlmoxarifadoSolicitacoesIdPrintRoute
  '/admin/core/empresas/$id/edit': typeof AdminCoreEmpresasIdEditRoute
  '/admin/core/unidades/$id/edit': typeof AdminCoreUnidadesIdEditRoute
  '/admin/core/users/$id/edit': typeof AdminCoreUsersIdEditRoute
  '/admin/rh/cargos/$id/edit': typeof AdminRhCargosIdEditRoute
  '/admin/rh/departamentos/$id/edit': typeof AdminRhDepartamentosIdEditRoute
  '/admin/almoxarifado/solicitacoes/$id/': typeof AdminAlmoxarifadoSolicitacoesIdIndexRoute
  '/admin/rh/departamentos/$id/': typeof AdminRhDepartamentosIdIndexRoute
  '/admin/almoxarifado/materiais/index/old': typeof AdminAlmoxarifadoMateriaisIndexOldRoute
  '/admin/almoxarifado/solicitacoes/index/old': typeof AdminAlmoxarifadoSolicitacoesIndexOldRoute
  '/admin/core/empresas/index/old': typeof AdminCoreEmpresasIndexOldRoute
  '/admin/core/unidades/index/old': typeof AdminCoreUnidadesIndexOldRoute
  '/admin/core/users/index/old': typeof AdminCoreUsersIndexOldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/superadmin'
    | '/login'
    | '/admin'
    | '/admin/core/configuracoes'
    | '/admin/user/alterar-senha'
    | '/admin/user/profile'
    | '/admin/almoxarifado'
    | '/admin/checklist'
    | '/admin/core'
    | '/admin/rh'
    | '/admin/almoxarifado/materiais/novo'
    | '/admin/almoxarifado/solicitacoes/nova'
    | '/admin/checklist/templates/novo'
    | '/admin/core/empresas/nova'
    | '/admin/core/unidades/nova'
    | '/admin/core/users/novo'
    | '/admin/rh/cargos/novo'
    | '/admin/rh/departamentos/novo'
    | '/admin/almoxarifado/materiais'
    | '/admin/almoxarifado/relatorios'
    | '/admin/almoxarifado/solicitacoes'
    | '/admin/checklist/avaliacoes'
    | '/admin/checklist/relatorios'
    | '/admin/checklist/templates'
    | '/admin/core/empresas'
    | '/admin/core/unidades'
    | '/admin/core/users'
    | '/admin/rh/avaliacoes-experiencia'
    | '/admin/rh/cargos'
    | '/admin/rh/departamentos'
    | '/admin/rh/equipes'
    | '/admin/rh/funcionarios'
    | '/admin/rh/importacao-pontoweb'
    | '/admin/almoxarifado/materiais/$id/edit'
    | '/admin/almoxarifado/solicitacoes/$id/print'
    | '/admin/core/empresas/$id/edit'
    | '/admin/core/unidades/$id/edit'
    | '/admin/core/users/$id/edit'
    | '/admin/rh/cargos/$id/edit'
    | '/admin/rh/departamentos/$id/edit'
    | '/admin/almoxarifado/solicitacoes/$id'
    | '/admin/rh/departamentos/$id'
    | '/admin/almoxarifado/materiais/index/old'
    | '/admin/almoxarifado/solicitacoes/index/old'
    | '/admin/core/empresas/index/old'
    | '/admin/core/unidades/index/old'
    | '/admin/core/users/index/old'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/superadmin'
    | '/login'
    | '/admin'
    | '/admin/core/configuracoes'
    | '/admin/user/alterar-senha'
    | '/admin/user/profile'
    | '/admin/almoxarifado'
    | '/admin/checklist'
    | '/admin/core'
    | '/admin/rh'
    | '/admin/almoxarifado/materiais/novo'
    | '/admin/almoxarifado/solicitacoes/nova'
    | '/admin/checklist/templates/novo'
    | '/admin/core/empresas/nova'
    | '/admin/core/unidades/nova'
    | '/admin/core/users/novo'
    | '/admin/rh/cargos/novo'
    | '/admin/rh/departamentos/novo'
    | '/admin/almoxarifado/materiais'
    | '/admin/almoxarifado/relatorios'
    | '/admin/almoxarifado/solicitacoes'
    | '/admin/checklist/avaliacoes'
    | '/admin/checklist/relatorios'
    | '/admin/checklist/templates'
    | '/admin/core/empresas'
    | '/admin/core/unidades'
    | '/admin/core/users'
    | '/admin/rh/avaliacoes-experiencia'
    | '/admin/rh/cargos'
    | '/admin/rh/departamentos'
    | '/admin/rh/equipes'
    | '/admin/rh/funcionarios'
    | '/admin/rh/importacao-pontoweb'
    | '/admin/almoxarifado/materiais/$id/edit'
    | '/admin/almoxarifado/solicitacoes/$id/print'
    | '/admin/core/empresas/$id/edit'
    | '/admin/core/unidades/$id/edit'
    | '/admin/core/users/$id/edit'
    | '/admin/rh/cargos/$id/edit'
    | '/admin/rh/departamentos/$id/edit'
    | '/admin/almoxarifado/solicitacoes/$id'
    | '/admin/rh/departamentos/$id'
    | '/admin/almoxarifado/materiais/index/old'
    | '/admin/almoxarifado/solicitacoes/index/old'
    | '/admin/core/empresas/index/old'
    | '/admin/core/unidades/index/old'
    | '/admin/core/users/index/old'
  id:
    | '__root__'
    | '/'
    | '/superadmin'
    | '/_auth/login'
    | '/admin/'
    | '/admin/core/configuracoes'
    | '/admin/user/alterar-senha'
    | '/admin/user/profile'
    | '/admin/almoxarifado/'
    | '/admin/checklist/'
    | '/admin/core/'
    | '/admin/rh/'
    | '/admin/almoxarifado/materiais/novo'
    | '/admin/almoxarifado/solicitacoes/nova'
    | '/admin/checklist/templates/novo'
    | '/admin/core/empresas/nova'
    | '/admin/core/unidades/nova'
    | '/admin/core/users/novo'
    | '/admin/rh/cargos/novo'
    | '/admin/rh/departamentos/novo'
    | '/admin/almoxarifado/materiais/'
    | '/admin/almoxarifado/relatorios/'
    | '/admin/almoxarifado/solicitacoes/'
    | '/admin/checklist/avaliacoes/'
    | '/admin/checklist/relatorios/'
    | '/admin/checklist/templates/'
    | '/admin/core/empresas/'
    | '/admin/core/unidades/'
    | '/admin/core/users/'
    | '/admin/rh/avaliacoes-experiencia/'
    | '/admin/rh/cargos/'
    | '/admin/rh/departamentos/'
    | '/admin/rh/equipes/'
    | '/admin/rh/funcionarios/'
    | '/admin/rh/importacao-pontoweb/'
    | '/admin/almoxarifado/materiais/$id/edit'
    | '/admin/almoxarifado/solicitacoes/$id/print'
    | '/admin/core/empresas/$id/edit'
    | '/admin/core/unidades/$id/edit'
    | '/admin/core/users/$id/edit'
    | '/admin/rh/cargos/$id/edit'
    | '/admin/rh/departamentos/$id/edit'
    | '/admin/almoxarifado/solicitacoes/$id/'
    | '/admin/rh/departamentos/$id/'
    | '/admin/almoxarifado/materiais/index/old'
    | '/admin/almoxarifado/solicitacoes/index/old'
    | '/admin/core/empresas/index/old'
    | '/admin/core/unidades/index/old'
    | '/admin/core/users/index/old'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuperadminRoute: typeof SuperadminRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoreConfiguracoesRoute: typeof AdminCoreConfiguracoesRoute
  AdminUserAlterarSenhaRoute: typeof AdminUserAlterarSenhaRoute
  AdminUserProfileRoute: typeof AdminUserProfileRoute
  AdminAlmoxarifadoIndexRoute: typeof AdminAlmoxarifadoIndexRoute
  AdminChecklistIndexRoute: typeof AdminChecklistIndexRoute
  AdminCoreIndexRoute: typeof AdminCoreIndexRoute
  AdminRhIndexRoute: typeof AdminRhIndexRoute
  AdminAlmoxarifadoMateriaisNovoRoute: typeof AdminAlmoxarifadoMateriaisNovoRoute
  AdminAlmoxarifadoSolicitacoesNovaRoute: typeof AdminAlmoxarifadoSolicitacoesNovaRoute
  AdminChecklistTemplatesNovoRoute: typeof AdminChecklistTemplatesNovoRoute
  AdminCoreEmpresasNovaRoute: typeof AdminCoreEmpresasNovaRoute
  AdminCoreUnidadesNovaRoute: typeof AdminCoreUnidadesNovaRoute
  AdminCoreUsersNovoRoute: typeof AdminCoreUsersNovoRoute
  AdminRhCargosNovoRoute: typeof AdminRhCargosNovoRoute
  AdminRhDepartamentosNovoRoute: typeof AdminRhDepartamentosNovoRoute
  AdminAlmoxarifadoMateriaisIndexRoute: typeof AdminAlmoxarifadoMateriaisIndexRoute
  AdminAlmoxarifadoRelatoriosIndexRoute: typeof AdminAlmoxarifadoRelatoriosIndexRoute
  AdminAlmoxarifadoSolicitacoesIndexRoute: typeof AdminAlmoxarifadoSolicitacoesIndexRoute
  AdminChecklistAvaliacoesIndexRoute: typeof AdminChecklistAvaliacoesIndexRoute
  AdminChecklistRelatoriosIndexRoute: typeof AdminChecklistRelatoriosIndexRoute
  AdminChecklistTemplatesIndexRoute: typeof AdminChecklistTemplatesIndexRoute
  AdminCoreEmpresasIndexRoute: typeof AdminCoreEmpresasIndexRoute
  AdminCoreUnidadesIndexRoute: typeof AdminCoreUnidadesIndexRoute
  AdminCoreUsersIndexRoute: typeof AdminCoreUsersIndexRoute
  AdminRhAvaliacoesExperienciaIndexRoute: typeof AdminRhAvaliacoesExperienciaIndexRoute
  AdminRhCargosIndexRoute: typeof AdminRhCargosIndexRoute
  AdminRhDepartamentosIndexRoute: typeof AdminRhDepartamentosIndexRoute
  AdminRhEquipesIndexRoute: typeof AdminRhEquipesIndexRoute
  AdminRhFuncionariosIndexRoute: typeof AdminRhFuncionariosIndexRoute
  AdminRhImportacaoPontowebIndexRoute: typeof AdminRhImportacaoPontowebIndexRoute
  AdminAlmoxarifadoMateriaisIdEditRoute: typeof AdminAlmoxarifadoMateriaisIdEditRoute
  AdminAlmoxarifadoSolicitacoesIdPrintRoute: typeof AdminAlmoxarifadoSolicitacoesIdPrintRoute
  AdminCoreEmpresasIdEditRoute: typeof AdminCoreEmpresasIdEditRoute
  AdminCoreUnidadesIdEditRoute: typeof AdminCoreUnidadesIdEditRoute
  AdminCoreUsersIdEditRoute: typeof AdminCoreUsersIdEditRoute
  AdminRhCargosIdEditRoute: typeof AdminRhCargosIdEditRoute
  AdminRhDepartamentosIdEditRoute: typeof AdminRhDepartamentosIdEditRoute
  AdminAlmoxarifadoSolicitacoesIdIndexRoute: typeof AdminAlmoxarifadoSolicitacoesIdIndexRoute
  AdminRhDepartamentosIdIndexRoute: typeof AdminRhDepartamentosIdIndexRoute
  AdminAlmoxarifadoMateriaisIndexOldRoute: typeof AdminAlmoxarifadoMateriaisIndexOldRoute
  AdminAlmoxarifadoSolicitacoesIndexOldRoute: typeof AdminAlmoxarifadoSolicitacoesIndexOldRoute
  AdminCoreEmpresasIndexOldRoute: typeof AdminCoreEmpresasIndexOldRoute
  AdminCoreUnidadesIndexOldRoute: typeof AdminCoreUnidadesIndexOldRoute
  AdminCoreUsersIndexOldRoute: typeof AdminCoreUsersIndexOldRoute
}
export interface FileServerRoutesByFullPath {
  '/api/upload': typeof ApiUploadServerRoute
  '/api/images/$': typeof ApiImagesSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/upload': typeof ApiUploadServerRoute
  '/api/images/$': typeof ApiImagesSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/upload': typeof ApiUploadServerRoute
  '/api/images/$': typeof ApiImagesSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/upload' | '/api/images/$' | '/api/trpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/upload' | '/api/images/$' | '/api/trpc/$'
  id: '__root__' | '/api/upload' | '/api/images/$' | '/api/trpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiUploadServerRoute: typeof ApiUploadServerRoute
  ApiImagesSplatServerRoute: typeof ApiImagesSplatServerRoute
  ApiTrpcSplatServerRoute: typeof ApiTrpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/': {
      id: '/admin/rh/'
      path: '/admin/rh'
      fullPath: '/admin/rh'
      preLoaderRoute: typeof AdminRhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/': {
      id: '/admin/core/'
      path: '/admin/core'
      fullPath: '/admin/core'
      preLoaderRoute: typeof AdminCoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checklist/': {
      id: '/admin/checklist/'
      path: '/admin/checklist'
      fullPath: '/admin/checklist'
      preLoaderRoute: typeof AdminChecklistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/almoxarifado/': {
      id: '/admin/almoxarifado/'
      path: '/admin/almoxarifado'
      fullPath: '/admin/almoxarifado'
      preLoaderRoute: typeof AdminAlmoxarifadoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/profile': {
      id: '/admin/user/profile'
      path: '/admin/user/profile'
      fullPath: '/admin/user/profile'
      preLoaderRoute: typeof AdminUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/alterar-senha': {
      id: '/admin/user/alterar-senha'
      path: '/admin/user/alterar-senha'
      fullPath: '/admin/user/alterar-senha'
      preLoaderRoute: typeof AdminUserAlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/configuracoes': {
      id: '/admin/core/configuracoes'
      path: '/admin/core/configuracoes'
      fullPath: '/admin/core/configuracoes'
      preLoaderRoute: typeof AdminCoreConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/importacao-pontoweb/': {
      id: '/admin/rh/importacao-pontoweb/'
      path: '/admin/rh/importacao-pontoweb'
      fullPath: '/admin/rh/importacao-pontoweb'
      preLoaderRoute: typeof AdminRhImportacaoPontowebIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/funcionarios/': {
      id: '/admin/rh/funcionarios/'
      path: '/admin/rh/funcionarios'
      fullPath: '/admin/rh/funcionarios'
      preLoaderRoute: typeof AdminRhFuncionariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/equipes/': {
      id: '/admin/rh/equipes/'
      path: '/admin/rh/equipes'
      fullPath: '/admin/rh/equipes'
      preLoaderRoute: typeof AdminRhEquipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/departamentos/': {
      id: '/admin/rh/departamentos/'
      path: '/admin/rh/departamentos'
      fullPath: '/admin/rh/departamentos'
      preLoaderRoute: typeof AdminRhDepartamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/cargos/': {
      id: '/admin/rh/cargos/'
      path: '/admin/rh/cargos'
      fullPath: '/admin/rh/cargos'
      preLoaderRoute: typeof AdminRhCargosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/avaliacoes-experiencia/': {
      id: '/admin/rh/avaliacoes-experiencia/'
      path: '/admin/rh/avaliacoes-experiencia'
      fullPath: '/admin/rh/avaliacoes-experiencia'
      preLoaderRoute: typeof AdminRhAvaliacoesExperienciaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/users/': {
      id: '/admin/core/users/'
      path: '/admin/core/users'
      fullPath: '/admin/core/users'
      preLoaderRoute: typeof AdminCoreUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/unidades/': {
      id: '/admin/core/unidades/'
      path: '/admin/core/unidades'
      fullPath: '/admin/core/unidades'
      preLoaderRoute: typeof AdminCoreUnidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/empresas/': {
      id: '/admin/core/empresas/'
      path: '/admin/core/empresas'
      fullPath: '/admin/core/empresas'
      preLoaderRoute: typeof AdminCoreEmpresasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checklist/templates/': {
      id: '/admin/checklist/templates/'
      path: '/admin/checklist/templates'
      fullPath: '/admin/checklist/templates'
      preLoaderRoute: typeof AdminChecklistTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checklist/relatorios/': {
      id: '/admin/checklist/relatorios/'
      path: '/admin/checklist/relatorios'
      fullPath: '/admin/checklist/relatorios'
      preLoaderRoute: typeof AdminChecklistRelatoriosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checklist/avaliacoes/': {
      id: '/admin/checklist/avaliacoes/'
      path: '/admin/checklist/avaliacoes'
      fullPath: '/admin/checklist/avaliacoes'
      preLoaderRoute: typeof AdminChecklistAvaliacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/almoxarifado/solicitacoes/': {
      id: '/admin/almoxarifado/solicitacoes/'
      path: '/admin/almoxarifado/solicitacoes'
      fullPath: '/admin/almoxarifado/solicitacoes'
      preLoaderRoute: typeof AdminAlmoxarifadoSolicitacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/almoxarifado/relatorios/': {
      id: '/admin/almoxarifado/relatorios/'
      path: '/admin/almoxarifado/relatorios'
      fullPath: '/admin/almoxarifado/relatorios'
      preLoaderRoute: typeof AdminAlmoxarifadoRelatoriosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/almoxarifado/materiais/': {
      id: '/admin/almoxarifado/materiais/'
      path: '/admin/almoxarifado/materiais'
      fullPath: '/admin/almoxarifado/materiais'
      preLoaderRoute: typeof AdminAlmoxarifadoMateriaisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/departamentos/novo': {
      id: '/admin/rh/departamentos/novo'
      path: '/admin/rh/departamentos/novo'
      fullPath: '/admin/rh/departamentos/novo'
      preLoaderRoute: typeof AdminRhDepartamentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/cargos/novo': {
      id: '/admin/rh/cargos/novo'
      path: '/admin/rh/cargos/novo'
      fullPath: '/admin/rh/cargos/novo'
      preLoaderRoute: typeof AdminRhCargosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/users/novo': {
      id: '/admin/core/users/novo'
      path: '/admin/core/users/novo'
      fullPath: '/admin/core/users/novo'
      preLoaderRoute: typeof AdminCoreUsersNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/unidades/nova': {
      id: '/admin/core/unidades/nova'
      path: '/admin/core/unidades/nova'
      fullPath: '/admin/core/unidades/nova'
      preLoaderRoute: typeof AdminCoreUnidadesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/empresas/nova': {
      id: '/admin/core/empresas/nova'
      path: '/admin/core/empresas/nova'
      fullPath: '/admin/core/empresas/nova'
      preLoaderRoute: typeof AdminCoreEmpresasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checklist/templates/novo': {
      id: '/admin/checklist/templates/novo'
      path: '/admin/checklist/templates/novo'
      fullPath: '/admin/checklist/templates/novo'
      preLoaderRoute: typeof AdminChecklistTemplatesNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/almoxarifado/solicitacoes/nova': {
      id: '/admin/almoxarifado/solicitacoes/nova'
      path: '/admin/almoxarifado/solicitacoes/nova'
      fullPath: '/admin/almoxarifado/solicitacoes/nova'
      preLoaderRoute: typeof AdminAlmoxarifadoSolicitacoesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/almoxarifado/materiais/novo': {
      id: '/admin/almoxarifado/materiais/novo'
      path: '/admin/almoxarifado/materiais/novo'
      fullPath: '/admin/almoxarifado/materiais/novo'
      preLoaderRoute: typeof AdminAlmoxarifadoMateriaisNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/users/index/old': {
      id: '/admin/core/users/index/old'
      path: '/admin/core/users/index/old'
      fullPath: '/admin/core/users/index/old'
      preLoaderRoute: typeof AdminCoreUsersIndexOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/unidades/index/old': {
      id: '/admin/core/unidades/index/old'
      path: '/admin/core/unidades/index/old'
      fullPath: '/admin/core/unidades/index/old'
      preLoaderRoute: typeof AdminCoreUnidadesIndexOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/empresas/index/old': {
      id: '/admin/core/empresas/index/old'
      path: '/admin/core/empresas/index/old'
      fullPath: '/admin/core/empresas/index/old'
      preLoaderRoute: typeof AdminCoreEmpresasIndexOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/almoxarifado/solicitacoes/index/old': {
      id: '/admin/almoxarifado/solicitacoes/index/old'
      path: '/admin/almoxarifado/solicitacoes/index/old'
      fullPath: '/admin/almoxarifado/solicitacoes/index/old'
      preLoaderRoute: typeof AdminAlmoxarifadoSolicitacoesIndexOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/almoxarifado/materiais/index/old': {
      id: '/admin/almoxarifado/materiais/index/old'
      path: '/admin/almoxarifado/materiais/index/old'
      fullPath: '/admin/almoxarifado/materiais/index/old'
      preLoaderRoute: typeof AdminAlmoxarifadoMateriaisIndexOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/departamentos/$id/': {
      id: '/admin/rh/departamentos/$id/'
      path: '/admin/rh/departamentos/$id'
      fullPath: '/admin/rh/departamentos/$id'
      preLoaderRoute: typeof AdminRhDepartamentosIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/almoxarifado/solicitacoes/$id/': {
      id: '/admin/almoxarifado/solicitacoes/$id/'
      path: '/admin/almoxarifado/solicitacoes/$id'
      fullPath: '/admin/almoxarifado/solicitacoes/$id'
      preLoaderRoute: typeof AdminAlmoxarifadoSolicitacoesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/departamentos/$id/edit': {
      id: '/admin/rh/departamentos/$id/edit'
      path: '/admin/rh/departamentos/$id/edit'
      fullPath: '/admin/rh/departamentos/$id/edit'
      preLoaderRoute: typeof AdminRhDepartamentosIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rh/cargos/$id/edit': {
      id: '/admin/rh/cargos/$id/edit'
      path: '/admin/rh/cargos/$id/edit'
      fullPath: '/admin/rh/cargos/$id/edit'
      preLoaderRoute: typeof AdminRhCargosIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/users/$id/edit': {
      id: '/admin/core/users/$id/edit'
      path: '/admin/core/users/$id/edit'
      fullPath: '/admin/core/users/$id/edit'
      preLoaderRoute: typeof AdminCoreUsersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/unidades/$id/edit': {
      id: '/admin/core/unidades/$id/edit'
      path: '/admin/core/unidades/$id/edit'
      fullPath: '/admin/core/unidades/$id/edit'
      preLoaderRoute: typeof AdminCoreUnidadesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/core/empresas/$id/edit': {
      id: '/admin/core/empresas/$id/edit'
      path: '/admin/core/empresas/$id/edit'
      fullPath: '/admin/core/empresas/$id/edit'
      preLoaderRoute: typeof AdminCoreEmpresasIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/almoxarifado/solicitacoes/$id/print': {
      id: '/admin/almoxarifado/solicitacoes/$id/print'
      path: '/admin/almoxarifado/solicitacoes/$id/print'
      fullPath: '/admin/almoxarifado/solicitacoes/$id/print'
      preLoaderRoute: typeof AdminAlmoxarifadoSolicitacoesIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/almoxarifado/materiais/$id/edit': {
      id: '/admin/almoxarifado/materiais/$id/edit'
      path: '/admin/almoxarifado/materiais/$id/edit'
      fullPath: '/admin/almoxarifado/materiais/$id/edit'
      preLoaderRoute: typeof AdminAlmoxarifadoMateriaisIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/images/$': {
      id: '/api/images/$'
      path: '/api/images/$'
      fullPath: '/api/images/$'
      preLoaderRoute: typeof ApiImagesSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuperadminRoute: SuperadminRoute,
  AuthLoginRoute: AuthLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCoreConfiguracoesRoute: AdminCoreConfiguracoesRoute,
  AdminUserAlterarSenhaRoute: AdminUserAlterarSenhaRoute,
  AdminUserProfileRoute: AdminUserProfileRoute,
  AdminAlmoxarifadoIndexRoute: AdminAlmoxarifadoIndexRoute,
  AdminChecklistIndexRoute: AdminChecklistIndexRoute,
  AdminCoreIndexRoute: AdminCoreIndexRoute,
  AdminRhIndexRoute: AdminRhIndexRoute,
  AdminAlmoxarifadoMateriaisNovoRoute: AdminAlmoxarifadoMateriaisNovoRoute,
  AdminAlmoxarifadoSolicitacoesNovaRoute:
    AdminAlmoxarifadoSolicitacoesNovaRoute,
  AdminChecklistTemplatesNovoRoute: AdminChecklistTemplatesNovoRoute,
  AdminCoreEmpresasNovaRoute: AdminCoreEmpresasNovaRoute,
  AdminCoreUnidadesNovaRoute: AdminCoreUnidadesNovaRoute,
  AdminCoreUsersNovoRoute: AdminCoreUsersNovoRoute,
  AdminRhCargosNovoRoute: AdminRhCargosNovoRoute,
  AdminRhDepartamentosNovoRoute: AdminRhDepartamentosNovoRoute,
  AdminAlmoxarifadoMateriaisIndexRoute: AdminAlmoxarifadoMateriaisIndexRoute,
  AdminAlmoxarifadoRelatoriosIndexRoute: AdminAlmoxarifadoRelatoriosIndexRoute,
  AdminAlmoxarifadoSolicitacoesIndexRoute:
    AdminAlmoxarifadoSolicitacoesIndexRoute,
  AdminChecklistAvaliacoesIndexRoute: AdminChecklistAvaliacoesIndexRoute,
  AdminChecklistRelatoriosIndexRoute: AdminChecklistRelatoriosIndexRoute,
  AdminChecklistTemplatesIndexRoute: AdminChecklistTemplatesIndexRoute,
  AdminCoreEmpresasIndexRoute: AdminCoreEmpresasIndexRoute,
  AdminCoreUnidadesIndexRoute: AdminCoreUnidadesIndexRoute,
  AdminCoreUsersIndexRoute: AdminCoreUsersIndexRoute,
  AdminRhAvaliacoesExperienciaIndexRoute:
    AdminRhAvaliacoesExperienciaIndexRoute,
  AdminRhCargosIndexRoute: AdminRhCargosIndexRoute,
  AdminRhDepartamentosIndexRoute: AdminRhDepartamentosIndexRoute,
  AdminRhEquipesIndexRoute: AdminRhEquipesIndexRoute,
  AdminRhFuncionariosIndexRoute: AdminRhFuncionariosIndexRoute,
  AdminRhImportacaoPontowebIndexRoute: AdminRhImportacaoPontowebIndexRoute,
  AdminAlmoxarifadoMateriaisIdEditRoute: AdminAlmoxarifadoMateriaisIdEditRoute,
  AdminAlmoxarifadoSolicitacoesIdPrintRoute:
    AdminAlmoxarifadoSolicitacoesIdPrintRoute,
  AdminCoreEmpresasIdEditRoute: AdminCoreEmpresasIdEditRoute,
  AdminCoreUnidadesIdEditRoute: AdminCoreUnidadesIdEditRoute,
  AdminCoreUsersIdEditRoute: AdminCoreUsersIdEditRoute,
  AdminRhCargosIdEditRoute: AdminRhCargosIdEditRoute,
  AdminRhDepartamentosIdEditRoute: AdminRhDepartamentosIdEditRoute,
  AdminAlmoxarifadoSolicitacoesIdIndexRoute:
    AdminAlmoxarifadoSolicitacoesIdIndexRoute,
  AdminRhDepartamentosIdIndexRoute: AdminRhDepartamentosIdIndexRoute,
  AdminAlmoxarifadoMateriaisIndexOldRoute:
    AdminAlmoxarifadoMateriaisIndexOldRoute,
  AdminAlmoxarifadoSolicitacoesIndexOldRoute:
    AdminAlmoxarifadoSolicitacoesIndexOldRoute,
  AdminCoreEmpresasIndexOldRoute: AdminCoreEmpresasIndexOldRoute,
  AdminCoreUnidadesIndexOldRoute: AdminCoreUnidadesIndexOldRoute,
  AdminCoreUsersIndexOldRoute: AdminCoreUsersIndexOldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiUploadServerRoute: ApiUploadServerRoute,
  ApiImagesSplatServerRoute: ApiImagesSplatServerRoute,
  ApiTrpcSplatServerRoute: ApiTrpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
